import Head from 'next/head'

export default function Contact() {
    return (
        <div>
            <Head>
                <title>WATOLINK</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <h1>Contact</h1>
        </div>
    )
}
