import Head from 'next/head'
import Image from 'next/image'

export default function About() {
    return (
        <div>
            <Head>
                <title>WATOLINK</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <h1>About</h1>
        </div>
    )
}
