import Head from 'next/head'

export default function About() {
    return (
        <div>
            <Head>
                <title>WATOLINK</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
        </div>
    )
}
