import styled from 'styled-components'
import Head from 'next/head'
import Image from 'next/image'
import BigGoose from '../public/logos/BigGoose.svg'
import Name from '../public/logos/Name.svg'
import SmallName from '../public/logos/SmallName.svg'
import SPONSORS from '../constants/sponsors'

const Container = styled.div`
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: space-evenly;
`

const ContentContainer = styled.div`
    margin: 30px 0px;
`

const HeroContainer = styled.div`
    width: 100%;
    height: 90vh;
    display: flex;
    justify-content: center;
    align-items: center;
    position: relative;
`

const ImageWrap = styled.span`
    position: absolute;
    top: 100px;
    right: 200px;
`

const InfoContainer = styled.div`
    position: relative;
    display: flex;
    padding: 0px 100px;
    align-items: center;
`

const Heading = styled.div`
    font: ${({ theme }) => theme.fonts.heading};
    color: ${({ theme }) => theme.colors.accent};
`

const Subheading = styled.div`
    font: ${({ theme }) => theme.fonts.subheading};
`

const Text = styled.div`
    font: ${({ theme }) => theme.fonts.small20};
    line-height: 2rem;
`

const InfoDiv = styled.div`
    width: 400px;
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    padding: 0px 70px;
`

const CarouselContainer = styled.div`
    display: flex;
    flex-direction: row;
    overflow: hidden;
    width: 100%;
    align-items: center;
    justify-content: center;
    padding: 0 50px;
`

const CarouselItem = styled.div`
    flex: none;
    width: 100%;
    transition: transform 0.5s ease;
`

const Info = ({ heading, subheading, src, children }) => (
    <InfoDiv>
        <div
            style={{
                display: 'flex',
                justifyContent: 'center',
                alignItems: 'center',
                height: '70px',
            }}
        >
            {src ? (
                <Image alt="Image" src={src} />
            ) : (
                <Heading>{heading}</Heading>
            )}
        </div>
        <Subheading>{subheading}</Subheading>
        <Text>{children}</Text>
    </InfoDiv>
)

const Divider = styled.div`
    width: 1px;
    height: 100%;
    border-left: 3px solid black;
    position: absolute;
    right: 50%;
`

const CaptionContainer = styled.div`
    text-align: center;
    padding: 0 50px;
`

const SponsorContainer = styled.div`
    display: flex;
    flex-direction: column;
    align-items: center;
`

const Sponsors = styled.div`
    display: flex;
    width: 100vw;
    justify-content: space-evenly;
`

export default function About() {
    return (
        <>
            <Head>
                <title>WATOLINK</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <Container>
                <HeroContainer>
                    <Image alt="WATOLINK name logo" src={Name} layout="fixed" />
                    <ImageWrap>
                        <Image
                            alt="WATOLINK big logo"
                            src={BigGoose}
                            layout="fixed"
                        />
                    </ImageWrap>
                </HeroContainer>
                <ContentContainer>
                    <InfoContainer>
                        <Info heading="30+" subheading="Members">
                            Future projects may involve developing our own
                            sensor technology and BCI hardware. The efforts of
                            this team could eventually go towards graduate
                            research.
                        </Info>
                        <Divider />
                        <Info src={SmallName} subheading="Future">
                            Scaling towards longer term projects involving
                            speech rendering to make telepathy and brain
                            controlled applications involving audio generation
                            and mind-to-AI communication commercially viable.
                        </Info>
                    </InfoContainer>
                </ContentContainer>
                <ContentContainer>
                    <CaptionContainer>
                        <Text>
                            WATOLINK offers students an opportunity to develop
                            applications involving action-classification via EEG
                            signal analysis and inference. Our team is currently
                            laying the groundwork for a project that we will
                            submit to the NeuroTechX Competition in 2022.
                        </Text>
                    </CaptionContainer>
                </ContentContainer>

                {/* <ContentContainer>
                    <CarouselContainer>
                        <CarouselItem>
                            <Image
                                alt="testing"
                                src="/logos/BigGoose.svg"
                                layout="fill"
                            />
                        </CarouselItem>
                    </CarouselContainer>
                </ContentContainer> */}

                <ContentContainer>
                    <SponsorContainer>
                        <Heading>OUR PARTNERS</Heading>
                        <Sponsors>
                            {SPONSORS.map((sponsor) => (
                                <Image
                                    key={sponsor.name}
                                    alt={sponsor.name}
                                    src={sponsor.src}
                                />
                            ))}
                        </Sponsors>
                    </SponsorContainer>
                </ContentContainer>
            </Container>
        </>
    )
}
