import Head from 'next/head'
import styled from 'styled-components'

const Container = styled.div`
    display: flex;
    flex-direction: column;
`

const Title = styled.div`
    color: ${({ theme }) => theme.colors.white};
    font: ${({ theme }) => theme.fonts.heading};
    background-color: ${({ theme }) => theme.colors.blue};
    opacity: 0.5;
    text-align: center;
    padding: 30px;
    margin-top: 50px;
    outline: ${({theme}) => theme.colors.blue};
    box-shadow: 0px 1px 6px black;
    margin-bottom: 50px;
`

const BodyText = styled.div`
    color: ${({ theme }) => theme.colors.black};
    font: ${({ theme }) => theme.fonts.medium24bold};
    text-align: center;
    white-space: pre;
`
const BottomText = styled.div`
    color: ${({ theme }) => theme.colors.blue};
    font: ${({ theme }) => theme.fonts.medium24bold};
    text-align: center;
    margin-top: 2%;
    margin-bottom: 2%;
`

const StyledCardDiv = styled.div`
    background-color: ${({ color }) => color};
    width: 100px;
    border-radius: 5px;
    outline: ${({theme}) => theme.colors.blue} solid 2px;
    opacity: 0.5;
    box-shadow: 0px 3px 2px black;
    padding: 30px;
`

export default function Projects() {
    return (
        <>
            {/* TODO: fix head */}
            <Head>
                <title>WATOLINK</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <Container>
                <Title>CURRENT PROJECTS</Title>
                <StyledCardDiv color={'white'}>
                    <img src={"/project_icons/bci_gaming_img.svg"} />
                </StyledCardDiv>
                <br></br>
                <BottomText>Stay Tuned!</BottomText>
            </Container>
        </>
    )
}
