import Head from 'next/head'
import styled from 'styled-components'

const Container = styled.div`
    display: flex;
    flex-direction: column;
`

const Title = styled.div`
    color: ${({ theme }) => theme.colors.blue};
    font: ${({ theme }) => theme.fonts.heading};
    text-align: center;
    padding-bottom: 50px;
`

const BodyText = styled.div`
    color: ${({ theme }) => theme.colors.black};
    font: ${({ theme }) => theme.fonts.medium24bold};
    text-align: center;
    white-space: pre;
`
const BottomText = styled.div`
    color: ${({ theme }) => theme.colors.blue};
    font: ${({ theme }) => theme.fonts.medium24bold};
    text-align: center;
    margin-top: 2%;
    margin-bottom: 2%;
`

export default function Projects() {
    return (
        <>
            {/* TODO: fix head */}
            <Head>
                <title>WATOLINK</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <Container>
                <Title>PROJECTS</Title>
                <BodyText>
                    We are currently developing our project submission towards
                    the NeuroTechX 2022 competition.
                </BodyText>
                <BodyText>
                    Showcase will be available after competition date.
                </BodyText>
                <br></br>
                <BottomText>Stay Tuned!</BottomText>
            </Container>
        </>
    )
}
